const DEFAULTS = {
  club:'assets/roc-logo.jpg', ffr:'assets/france-rugby-logo.jpg', home:'assets/home-rugby.jpg', match:'assets/stadium.jpg', pile:'assets/coin-pile.jpg', face:'assets/coin-face.jpg'
};
const COLORS=['#e2231a','#111111','#f2b705','#1769c2','#23c56e','#8e44ad','#e67e22'];
let current=null, ticker=null, actionStack=[], exclusions={a:[],b:[]}, coinBusy=false;
const $=id=>document.getElementById(id);
function get(k){return localStorage.getItem(k)} function set(k,v){localStorage.setItem(k,v)}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');applyBranding();if(id==='history')renderHistory()}
function src(k){return get('brand_'+k)||DEFAULTS[k]}
function img(el,k){const x=$(el);if(x)x.src=src(k)}
function applyBranding(){['club-logo-setup','club-logo-match','club-logo-results'].forEach(i=>img(i,'club'));['ffr-logo-setup','ffr-logo-match','ffr-logo-results'].forEach(i=>img(i,'ffr'));img('home-bg','home');img('match-bg','match');img('coin-pile-img','pile');img('coin-face-img','face')}
async function pickImage(key){
  try{
    let dataUrl='';
    if(window.Capacitor && Capacitor.Plugins && Capacitor.Plugins.Camera){
      const r=await Capacitor.Plugins.Camera.pickImages({quality:75,limit:1});
      if(r.photos && r.photos[0]) dataUrl=r.photos[0].webPath;
    }
    if(!dataUrl){$(key+'-file').click();return}
    set('brand_'+key,dataUrl);applyBranding();toast('Image enregistrée');
  }catch(e){toast('Sélection annulée')}
}
function upload(e,key){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=950;let w=im.width,h=im.height;if(w>max){h=Math.round(h*max/w);w=max}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);try{set('brand_'+key,c.toDataURL('image/jpeg',.75));applyBranding();toast('Image enregistrée')}catch(err){toast('Image trop lourde')}};im.src=r.result};r.readAsDataURL(f)}
function resetBranding(){Object.keys(DEFAULTS).forEach(k=>localStorage.removeItem('brand_'+k));applyBranding();toast('Images réinitialisées')}
function toast(s){const e=$('toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1900)}
function kit(t,cls='kit'){const a=t.c1||'#e2231a',b=t.c2||a;const p=t.pattern==='stripe'?`<path d="M19 8 L37 8 L48 18 L42 26 L37 22 L37 70 L19 70 L19 22 L14 26 L8 18 Z" fill="${a}"/><path d="M18 19 L31 11 L38 18 L38 30 L29 23 L18 30 Z" fill="${b}"/><path d="M18 42 L38 32 L38 43 L18 53 Z" fill="${b}"/>`:`<path d="M19 8 L37 8 L48 18 L42 26 L37 22 L37 70 L19 70 L19 22 L14 26 L8 18 Z" fill="${a}"/><path d="M14 17 L22 10 L40 70 L31 70 Z" fill="${b}"/>`;return `<svg class="${cls}" viewBox="0 0 56 78">${p}<path d="M19 8 L37 8 L48 18 L42 26 L37 22 L37 70 L19 70 L19 22 L14 26 L8 18 Z" fill="none" stroke="#101010" stroke-width="3"/><path d="M21 8 Q28 20 35 8" fill="none" stroke="#101010" stroke-width="3"/></svg>`}
let draft=[];
function newPlateau(n=3){draft=Array.from({length:n},(_,i)=>({name:'Équipe '+String.fromCharCode(65+i),c1:COLORS[i%COLORS.length],c2:i===0?'#111111':'#ffffff',pattern:i%2?'slash':'stripe'}));renderTeams();show('setup')}
function renderTeams(){$('teams').innerHTML=draft.map((t,i)=>`<div class="teamrow"><span id="k${i}">${kit(t,'kit previewkit')}</span><input class="tn" value="${t.name}"><select class="tp" onchange="previewTeam(${i})"><option value="stripe" ${t.pattern==='stripe'?'selected':''}>Bandes / chevrons</option><option value="slash" ${t.pattern==='slash'?'selected':''}>Bande oblique</option></select><input class="c1" type="color" value="${t.c1}" onchange="previewTeam(${i})"><input class="c2" type="color" value="${t.c2}" onchange="previewTeam(${i})"><button class="x" onclick="removeTeam(${i})">×</button></div>`).join('')}
function readDraft(){document.querySelectorAll('.teamrow').forEach((r,i)=>{draft[i].name=r.querySelector('.tn').value||'Équipe '+(i+1);draft[i].c1=r.querySelector('.c1').value;draft[i].c2=r.querySelector('.c2').value;draft[i].pattern=r.querySelector('.tp').value})}
function previewTeam(i){readDraft();$('k'+i).innerHTML=kit(draft[i],'kit previewkit')}
function addTeam(){readDraft();draft.push({name:'Équipe '+String.fromCharCode(65+draft.length),c1:COLORS[draft.length%COLORS.length],c2:'#ffffff',pattern:'slash'});renderTeams()}
function removeTeam(i){if(draft.length<3)return toast('Minimum 3 équipes');draft.splice(i,1);renderTeams()}
function createTournament(){readDraft();const pairs=[];for(let i=0;i<draft.length;i++)for(let j=i+1;j<draft.length;j++)pairs.push([i,j]);const seq=[];pairs.forEach((p,i)=>seq.push({id:'m'+i+'h1',match:'m'+i,a:p[0],b:p[1],half:1,done:false,sa:0,sb:0}));pairs.forEach((p,i)=>seq.push({id:'m'+i+'h2',match:'m'+i,a:p[0],b:p[1],half:2,done:false,sa:0,sb:0}));current={name:$('pname').value||'Plateau',category:$('category').value,duration:+$('duration').value||15,teams:draft,seq,created:new Date().toISOString()};set('current_tournament',JSON.stringify(current));renderSchedule();show('schedule')}
function resume(){const s=get('current_tournament');if(!s)return toast('Aucun plateau en cours');current=JSON.parse(s);renderSchedule();show('schedule')}
function renderSchedule(){if(!current)return;$('sch-title').textContent=current.name;const block=h=>`<section><h3>${h===1?'1ères mi-temps':'2èmes mi-temps'}</h3>${current.seq.filter(s=>s.half===h).map(s=>{const A=current.teams[s.a],B=current.teams[s.b];return `<div class="matchrow ${s.done?'done':''}"><span>${kit(A,'kit mini')} ${A.name}<b>vs</b>${kit(B,'kit mini')} ${B.name}</span>${s.done?`<em>✓ ${s.sa} - ${s.sb}</em>`:`<button onclick="openCoin('${s.id}')">Démarrer</button>`}</div>`}).join('')}</section>`;$('schedule-list').innerHTML=block(1)+block(2);$('final').style.display=current.seq.every(s=>s.done)?'block':'none'}
function openCoin(id){current.active=id;set('current_tournament',JSON.stringify(current));$('coin').style.transform='rotateY(0deg)';$('coin-result').innerHTML='<b>PRÊT ?</b><span>Appuie sur lancer</span>';show('coin')}
function toss(){if(coinBusy)return;coinBusy=true;const r=Math.random()<.5?'PILE':'FACE',angle=(7+(Math.random()<.5?0:1))*360+(r==='FACE'?180:0);$('coin').classList.add('spin');setTimeout(()=>{$('coin').classList.remove('spin');$('coin').style.transform=`rotateY(${angle}deg)`;$('coin-result').innerHTML=`<b>RÉSULTAT : ${r}</b><span>Le tirage est terminé</span>`;beep(350,r==='PILE'?500:700);coinBusy=false;setTimeout(()=>startMatch(),1000)},2100)}
function startMatch(){const s=current.seq.find(x=>x.id===current.active);s.left=0;s.right=0;s.seconds=current.duration*60;s.running=false;actionStack=[];exclusions={a:[],b:[]};const A=current.teams[s.a],B=current.teams[s.b];$('mname').textContent=current.name;$('mcat').textContent=current.category;$('aname').textContent=A.name;$('bname').textContent=B.name;$('akit').innerHTML=kit(A,'kit bigkit');$('bkit').innerHTML=kit(B,'kit bigkit');$('apanel').style.borderColor=A.c1;$('bpanel').style.borderColor=B.c1;$('half').textContent=s.half===1?'1ère MI-TEMPS':'2ème MI-TEMPS';updateMatch();show('match');wake()}
function fmt(x){return String(x/60|0).padStart(2,'0')+':'+String(x%60).padStart(2,'0')}
function updateMatch(){const s=current.seq.find(x=>x.id===current.active);$('ascore').textContent=s.left;$('bscore').textContent=s.right;$('timer').textContent=fmt(s.seconds);$('timer').classList.toggle('go',s.running);$('status').textContent=s.seconds===0?'TEMPS ÉCOULÉ':s.running?'MATCH EN COURS':'EN PAUSE';renderExcl()}
function toggle(){const s=current.seq.find(x=>x.id===current.active);if(s.seconds===0)return;s.running=!s.running;if(s.running&&!ticker)ticker=setInterval(tick,1000);updateMatch()}
function tick(){const s=current&&current.seq.find(x=>x.id===current.active);if(!s||!s.running)return;if(s.seconds)s.seconds--;['a','b'].forEach(k=>exclusions[k].forEach(e=>{if(e.s&&!e.done){e.s--;if(!e.s){e.done=true;beep(350,440)}}}));if(!s.seconds){s.running=false;beep(700,660)}updateMatch()}
function point(side,n){const s=current.seq.find(x=>x.id===current.active);s[side==='a'?'left':'right']=Math.max(0,s[side==='a'?'left':'right']+n);actionStack.push({side,n});updateMatch()}
function exclusion(side){const e={s:120,done:false};exclusions[side].push(e);actionStack.push({side,e,ex:true});updateMatch()}
function renderExcl(){['a','b'].forEach(k=>{$('ex'+k).innerHTML=exclusions[k].map(e=>`<i>${e.done?'RETOUR':'⏱ '+fmt(e.s)}</i>`).join('')})}
function undo(){const a=actionStack.pop();if(!a)return;if(a.ex)exclusions[a.side]=exclusions[a.side].filter(e=>e!==a.e);else point(a.side,-a.n);updateMatch()}
function validateMatch(){const s=current.seq.find(x=>x.id===current.active);if(!confirm('Valider cette séquence ?'))return;s.running=false;s.done=true;s.sa=s.left;s.sb=s.right;set('current_tournament',JSON.stringify(current));if(ticker){clearInterval(ticker);ticker=null}renderSchedule();show('schedule')}
function beep(ms,f){try{const c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=f;g.gain.value=.16;o.start();setTimeout(()=>o.stop(),ms)}catch(e){}if(navigator.vibrate)navigator.vibrate(ms)} async function wake(){try{await navigator.wakeLock.request('screen')}catch(e){}}
function stats(){const st=current.teams.map((t,i)=>({t,i,w:0,d:0,l:0,pf:0,pa:0})),m={};current.seq.forEach(s=>{if(!m[s.match])m[s.match]={a:s.a,b:s.b,sa:0,sb:0};m[s.match].sa+=s.sa;m[s.match].sb+=s.sb});Object.values(m).forEach(x=>{st[x.a].pf+=x.sa;st[x.a].pa+=x.sb;st[x.b].pf+=x.sb;st[x.b].pa+=x.sa;if(x.sa>x.sb){st[x.a].w++;st[x.b].l++}else if(x.sa<x.sb){st[x.b].w++;st[x.a].l++}else{st[x.a].d++;st[x.b].d++}});st.forEach(x=>{x.pts=x.w*3+x.d;x.diff=x.pf-x.pa});st.sort((a,b)=>b.pts-a.pts||b.diff-a.diff||b.pf-a.pf);return{st,m}}
function results(){const{st,m}=stats();$('rank').innerHTML='<h2>Classement final</h2><table><tr><th>#</th><th>Équipe</th><th>V</th><th>N</th><th>D</th><th>Diff</th><th>Pts</th></tr>'+st.map((x,i)=>`<tr><td>${i+1}</td><td>${x.t.name}</td><td>${x.w}</td><td>${x.d}</td><td>${x.l}</td><td>${x.diff}</td><td>${x.pts}</td></tr>`).join('')+'</table>';show('results')}
function exportCSV(){const{st}=stats();let x='Rang,Equipe,V,N,D,Pour,Contre,Diff,Pts\n';st.forEach((s,i)=>x+=`${i+1},${s.t.name},${s.w},${s.d},${s.l},${s.pf},${s.pa},${s.diff},${s.pts}\n`);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([x],{type:'text/csv'}));a.download='plateau-rugby.csv';a.click()}
function archive(){const h=JSON.parse(get('history')||'[]');h.unshift({name:current.name,category:current.category,date:current.created});set('history',JSON.stringify(h));localStorage.removeItem('current_tournament');current=null;show('home')}
function renderHistory(){const h=JSON.parse(get('history')||'[]');$('hist').innerHTML=h.length?h.map(x=>`<div class="matchrow done"><b>${x.name}</b><small>${x.category} — ${new Date(x.date).toLocaleDateString('fr-FR')}</small></div>`).join(''):'<p>Aucun plateau archivé.</p>'}
